ALTER TABLE jobs ADD COLUMN location TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN href TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN skills_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE jobs ADD COLUMN published_at TEXT NOT NULL DEFAULT '';
